# Application configuration
spring:
  application:
    name: ${template.manager.service.name}
  profiles:
    active: ${spring.profiles.active}
  sql:
    init:
      mode: always
      continue-on-error: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://example.com/.well-known/jwks.json

# Server configuration
server:
  error:
    include-message: always
    include-binding-errors: always

# SpringDoc configuration
springdoc:
  swagger-ui:
    enabled: ${springdoc.swagger-ui.enabled}
    path: /swagger-ui.html
  api-docs:
    enabled: ${springdoc.api-docs.enabled}
  packages-to-scan: com.hoatv.template.management

# Management configuration
management:
  metrics:
    tags:
      application: ${template.manager.service.name}
  endpoints:
    web:
      exposure:
        include: "*"
