name: send-submodule-updates-to-parent-repo-ci

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.ACCESS_TOKEN || github.token }}
          filters: |
            backend:
              - 'template-manager-backend/**'
              - 'pom.xml'
              - '.github/workflows/**'
            ui:
              - 'template-manager-ui/**'
              - '.github/workflows/**'

  Update:
    needs: changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: hvantran/project-management
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "tranvanhoactk34@gmail.com"
          git config user.name "GitHub Actions - update template-management-app submodule"
          git add --all
          git commit -m "Update template-management-app submodules" || echo "No changes to commit"
      - uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 5
          command: git pull --rebase && git push
      - name: Github REST API Call to make template-manager-backend-ci service build
        if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.backend == 'true' }}
        env:
          CI_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PARENT_REPO: project-management
          PARENT_BRANCH: main
          WORKFLOW_ID: template-manager-backend-ci.yaml
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/hvantran/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
      - name: Github REST API Call to make template-manager-ui-ci service build
        if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.ui == 'true' }}
        env:
          CI_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PARENT_REPO: project-management
          PARENT_BRANCH: main
          WORKFLOW_ID: template-manager-ui-ci.yaml
        run: |
          curl -fL --retry 3 -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ env.CI_TOKEN }}" https://api.github.com/repos/hvantran/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches -d '{"ref":"${{ env.PARENT_BRANCH }}"}'
